CREATE TYPE zchar;

CREATE FUNCTION zchar_in(cstring) RETURNS zchar AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION zchar_out(zchar) RETURNS cstring AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;

CREATE TYPE zchar (
    internallength = -1,
    input = zchar_in,
    output = zchar_out
);

CREATE FUNCTION zchar_bytea(zchar) RETURNS bytea AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION bytea_zchar(bytea) RETURNS zchar AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE CAST ( bytea AS zchar) WITHOUT FUNCTION;
CREATE CAST ( zchar AS bytea) WITHOUT FUNCTION;
CREATE CAST (zchar as varchar) WITH INOUT AS ASSIGNMENT;
CREATE CAST (varchar AS zchar) WITH INOUT AS ASSIGNMENT;
